version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "S3SAM112"
s3_bucket = "sambucket000"
s3_prefix = "S3SAM112"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
